const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createHash}=require('node:crypto');
const {openDraftV2}=require('../dist/session/draft-store-v2');
const {materializeMarkdownDraftSnapshotV2,renderEvidenceBlockV1}=require('../dist/session/markdown-draft-snapshot');
const {compareAndSwapAggregateHeadV1}=require('../dist/session/aggregate-head');
const {canonicalizeChangePlanV2,assignChangePlanV2}=require('../dist/session/change-plan-v2');
const {runSubmissionPipelineV2,SubmissionPipelineErrorV2}=require('../dist/session/submission-pipeline-v2');
const {publishMutation}=require('../dist/world/publish');
const {readPublishedWorld}=require('../dist/world/read');

const temporary=(t)=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'submission-v2-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;};
const write=(root,relative,content)=>{const target=path.join(root,...relative.split('/'));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content);};
const sha=(bytes)=>createHash('sha256').update(bytes).digest('hex');
const session=(root)=>({id:'session_pipeline',kind:'init',root:path.join(root,'transient'),contextDir:'',conversationDir:'',sendConfig:'',requestsDir:'',summaryConfigPath:'',summaryPromptPath:'',pinned:null,day:null});
function installValidInit(root){const files={'canon/premise.md':'','canon/rules.md':'','canon/style.md':'','canon/user-role.md':'','state/world.yaml':'schemaVersion: 1\ntitle: Pipeline World\nstatus: active\n','state/calendar.yaml':'schemaVersion: 1\ncurrentDay: null\nelapsed: null\n','state/progress.yaml':'schemaVersion: 1\nactiveArcIds: []\n','state/variables.yaml':'schemaVersion: 1\nvariables: {}\n','characters/index.yaml':'schemaVersion: 1\nids: []\n','locations/index.yaml':'schemaVersion: 1\nids: []\n','arcs/index.yaml':'schemaVersion: 1\nids: []\n','memory/short-term.md':'','memory/long-term.md':'','memory/facts.yaml':'schemaVersion: 1\nfacts: []\n','memory/unresolved-threads.yaml':'schemaVersion: 1\nthreads: []\n','memory/important-events.yaml':'schemaVersion: 1\nevents: []\n','story-seeds/active.yaml':'schemaVersion: 1\nseeds: []\n'};for(const [relative,content] of Object.entries(files))write(root,relative,content);}
async function fixture(t){const root=temporary(t),runtimeRoot=path.join(root,'runtime'),worldRoot=path.join(root,'world'),draft=await openDraftV2({runtimeRoot,kind:'init',worldIdentity:'world-key',baseCommitId:null,baseRootTreeHash:null,targetDay:null}),base=await draft.snapshot(),turnId='turn1',generationId='generation1',userInput='Create Pipeline World.',block=renderEvidenceBlockV1({turnId,generationId,userInput,acceptedResponse:'I will create it.',curatorNote:'Captured explicit title.'}),brief=Buffer.from('# Dayloom Draft Brief\n\nCreate Pipeline World.\n'),snapshot=await materializeMarkdownDraftSnapshotV2({slotRoot:draft.root,draftId:draft.id,meta:draft.meta(),brief,evidence:Buffer.concat([fs.readFileSync(path.join(base.root,'evidence.md')),block])}),active=session(root),conversationId='conv1';fs.mkdirSync(path.join(draft.root,'sessions',active.id,'conversations',conversationId),{recursive:true});await compareAndSwapAggregateHeadV1({slotRoot:draft.root,expectedRevision:0,next:{schemaVersion:1,revision:1,draftHash:snapshot.hash,activeSession:{sessionId:active.id,conversationId,pendingDraftSync:null}}});const turn={schemaVersion:1,turnId,sessionId:active.id,userInput,baseConversationId:'conv0',baseDraftHash:base.hash,generationAttempts:[{generationId,operationId:'operation1',attempt:1,responseText:'I will create it.',complete:true,disposition:'committed',verdict:{response:{verdict:'ACCEPT'},draft:{verdict:'UPDATE',evidence:'User requested the initial World.'}}}],acceptedGenerationId:generationId,draftVerdict:'UPDATE',resultDraftHash:snapshot.hash,curationAttempts:[],terminalStatus:'committed'};const plan=canonicalizeChangePlanV2({schemaVersion:2,sessionKind:'init',baseDraftHash:snapshot.hash,baseWorldCommitId:null,targetDay:null,changes:[{localKey:'world-profile',action:'create',resourceKind:'world-profile',targetId:null,parentLocalKey:null,evidence:[{source:'brief',startLine:1,endLine:1,sha256:sha(Buffer.from('# Dayloom Draft Brief\n'))},{source:'evidence',turnId,field:'user-input',sha256:sha(Buffer.from(userInput))}]}]}),assignment=assignChangePlanV2(plan,null);return{root,runtimeRoot,worldRoot,draft,active,turn,plan,assignment};}

test('Submission V2 seals evidence, validates Candidate, publishes Audit V2, and archives Markdown Draft',async(t)=>{const f=await fixture(t),stages=[];const result=await runSubmissionPipelineV2({worldRoot:f.worldRoot,transientRoot:f.active.root,session:f.active,draft:f.draft,turns:[f.turn],planner:{async plan(){return{plan:f.plan,assignment:f.assignment};}},converter:{async run(input){installValidInit(input.candidateRoot);}},reviewer:{async review(){return{raw:{advisory:[]},advisory:[]};}},stage(stage,attempt){stages.push(`${stage}:${attempt}`);},publish:(request)=>publishMutation(f.worldRoot,request)});assert.equal(result.published.view.title,'Pipeline World');assert.equal((await readPublishedWorld(f.worldRoot)).commit.revision,1);assert.deepEqual(stages,['plan:1','convert:1','validate:1','review:1','diff:1','publish:1']);assert.equal(fs.existsSync(f.draft.root),false);assert.equal(fs.existsSync(path.join(f.runtimeRoot,'drafts','archive',f.draft.id,'snapshot','brief.md')),true);for(const relative of['meta.json','change-plan.json','assignment.json','candidate-diff.json'])assert.ok(result.published.tree.entries.some((entry)=>entry.path===`audit/sessions/${f.active.id}/${relative}`));});

test('Submission V2 bounds repair, preserves World, and keeps authoritative Draft on repeated diagnostics',async(t)=>{const f=await fixture(t);let calls=0;await assert.rejects(()=>runSubmissionPipelineV2({worldRoot:f.worldRoot,transientRoot:f.active.root,session:f.active,draft:f.draft,turns:[f.turn],planner:{async plan(){return{plan:f.plan,assignment:f.assignment};}},converter:{async run(){calls+=1;}},reviewer:{async review(){throw new Error('must not review');}},stage(){},publish:(request)=>publishMutation(f.worldRoot,request)}),(error)=>error instanceof SubmissionPipelineErrorV2&&error.code==='CANDIDATE_INVALID');assert.equal(calls,2);assert.equal(fs.existsSync(path.join(f.worldRoot,'current.json')),false);assert.equal(fs.existsSync(f.draft.root),true);});
