const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {installAggregateHeadV1}=require('../dist/session/aggregate-head');
const {INITIAL_BRIEF_V2,INITIAL_EVIDENCE_V2,materializeMarkdownDraftSnapshotV2}=require('../dist/session/markdown-draft-snapshot');
const {runTurnCoordinatorV1}=require('../dist/session/turn-coordinator');
const temporary=(t)=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'turn-coordinator-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;};
const meta={schemaVersion:2,draftId:'draft1',sourceFormat:'markdown-v2',kind:'revise',worldIdentity:'world1',baseCommitId:'commit1',baseRootTreeHash:'1'.repeat(64),targetDay:null,createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z'};
test('Turn Coordinator linearizes accepted response before Draft update',async(t)=>{const slotRoot=temporary(t),baseSnapshot=await materializeMarkdownDraftSnapshotV2({slotRoot,draftId:'draft1',meta,brief:Buffer.from(INITIAL_BRIEF_V2),evidence:Buffer.from(INITIAL_EVIDENCE_V2)}),sessionId='session1',conversationId='conv1';
 fs.mkdirSync(path.join(slotRoot,'sessions',sessionId,'conversations',conversationId),{recursive:true});await installAggregateHeadV1({slotRoot,head:{schemaVersion:1,revision:0,draftHash:baseSnapshot.hash,activeSession:null}});const {compareAndSwapAggregateHeadV1}=require('../dist/session/aggregate-head');const activeHead=await compareAndSwapAggregateHeadV1({slotRoot,expectedRevision:0,next:{schemaVersion:1,revision:1,draftHash:baseSnapshot.hash,activeSession:{sessionId,conversationId,pendingDraftSync:null}}});
 const conv2='conv2';fs.mkdirSync(path.join(slotRoot,'sessions',sessionId,'conversations',conv2));const nextSnapshot=await materializeMarkdownDraftSnapshotV2({slotRoot,draftId:'draft1',meta,brief:Buffer.from(INITIAL_BRIEF_V2+'accepted\n'),evidence:Buffer.from(INITIAL_EVIDENCE_V2+'evidence\n')});const events=[];
 const result=await runTurnCoordinatorV1({slotRoot,sessionId,userInput:'change',base:activeHead,effects:{generate:async(operationId)=>({generationId:'gen1',operationId,responseText:'answer',conversationId:conv2}),arbitrate:async(operationId)=>({operationId,verdict:{decision:'ACCEPT',draft:'UPDATE'}}),curate:async(operationId)=>({operationId,snapshot:nextSnapshot}),persist:async()=>{},emit:(event)=>events.push(event),cancelled:()=>false}});
 assert.equal(result.status,'committed');assert.equal(result.head.revision,3);assert.equal(result.head.draftHash,nextSnapshot.hash);assert.deepEqual(events.filter((e)=>e.type==='turn.commit').map((e)=>e.commit),['response','draft']);assert.equal(events.at(-1).type,'turn.terminal');
});

test('Turn Coordinator supersedes one rejected generation and commits only the repaired Conversation',async(t)=>{const slotRoot=temporary(t),snapshot=await materializeMarkdownDraftSnapshotV2({slotRoot,draftId:'draft1',meta,brief:Buffer.from(INITIAL_BRIEF_V2),evidence:Buffer.from(INITIAL_EVIDENCE_V2)}),sessionId='session1',conversationId='conv1';fs.mkdirSync(path.join(slotRoot,'sessions',sessionId,'conversations',conversationId),{recursive:true});await installAggregateHeadV1({slotRoot,head:{schemaVersion:1,revision:0,draftHash:snapshot.hash,activeSession:null}});const {compareAndSwapAggregateHeadV1}=require('../dist/session/aggregate-head'),base=await compareAndSwapAggregateHeadV1({slotRoot,expectedRevision:0,next:{schemaVersion:1,revision:1,draftHash:snapshot.hash,activeSession:{sessionId,conversationId,pendingDraftSync:null}}});for(const id of['conv_rejected','conv_repaired'])fs.mkdirSync(path.join(slotRoot,'sessions',sessionId,'conversations',id));const events=[];let generated=0;const result=await runTurnCoordinatorV1({slotRoot,sessionId,userInput:'change',base,effects:{generate:async(operationId)=>{generated+=1;return{generationId:`gen${generated}`,operationId,responseText:`answer${generated}`,conversationId:generated===1?'conv_rejected':'conv_repaired'};},arbitrate:async(operationId,_response,attempt)=>({operationId,verdict:attempt===1?{decision:'REJECT',repairConstraint:'be precise'}:{decision:'ACCEPT',draft:'KEEP'}}),curate:async()=>{throw new Error('KEEP must not curate');},persist:async()=>{},emit:(event)=>events.push(event),cancelled:()=>false}});assert.equal(result.status,'committed');assert.equal(result.head.activeSession.conversationId,'conv_repaired');assert.equal(result.head.draftHash,snapshot.hash);assert.deepEqual(result.record.generationAttempts.map((item)=>item.disposition),['superseded','committed']);assert.equal(events.filter((event)=>event.type==='operation.started'&&event.kind==='response').length,2);});
