import { randomUUID } from 'node:crypto';
import { mkdir, readFile, readdir, rm } from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import { hashBlobV1 } from '@dayloom/archive-protocol';
import type { CoreSession } from './common';
import type { DraftHandleV2 } from './draft-store-v2';
import { hashChangePlanV2, type ChangePlanAssignmentV2, type ChangePlanV2 } from './change-plan-v2';
import { SESSION_FILE_LIMITS } from './file-limits';
import { sortDiagnosticsV1, type ValidationIssueV1 } from './diagnostics';
import { assembleCandidateV1, validateCandidateV1, type CandidateControlV1 } from '../world/candidate';
import { readCandidateWorkspaceV1 } from '../world/candidate-workspace';
import { readTextDocument, type PublishedWorld } from '../world/read';
import type { WorldChange } from '../world/publish';
import { buildSubmissionAuditV2, exportVisibleTranscriptV1, type SubmissionAuditInputV2 } from '../world/builders/audit';
import type { TurnAuditV1 } from './turn-record';
import { verifyChangePlanEvidenceV2 } from './change-evidence-v2';

export type SubmissionStageV2='plan'|'convert'|'validate'|'repair'|'review'|'diff'|'publish';
export interface SubmissionPlannerV2{plan(input:{session:CoreSession;draft:Awaited<ReturnType<DraftHandleV2['snapshot']>>}):Promise<{plan:Readonly<ChangePlanV2>;assignment:Readonly<ChangePlanAssignmentV2>}>}
export interface SubmissionConverterV2{run(input:{phase:'convert'|'repair';attempt:number;session:CoreSession;draft:Awaited<ReturnType<DraftHandleV2['snapshot']>>;plan:Readonly<ChangePlanV2>;assignment:Readonly<ChangePlanAssignmentV2>;candidateRoot:string;diagnostics:readonly ValidationIssueV1[]}):Promise<void>}
export interface SubmissionReviewerV2{review(input:{session:CoreSession;draft:Awaited<ReturnType<DraftHandleV2['snapshot']>>;plan:Readonly<ChangePlanV2>;assignment:Readonly<ChangePlanAssignmentV2>;candidateRoot:string}):Promise<{raw:unknown;advisory:readonly ValidationIssueV1[]}>}
export class SubmissionPipelineErrorV2 extends Error{constructor(readonly code:'CONVERSION_FAILED'|'CANDIDATE_INVALID'|'DRAFT_CONFLICT',message:string,readonly diagnostics:readonly ValidationIssueV1[]=[],options?:ErrorOptions){super(message,options);this.name='SubmissionPipelineErrorV2';}}

export async function runSubmissionPipelineV2(input:{worldRoot:string;transientRoot:string;session:CoreSession;draft:DraftHandleV2;turns:readonly Readonly<TurnAuditV1>[];planner:SubmissionPlannerV2;converter:SubmissionConverterV2;reviewer:SubmissionReviewerV2;publish(request:{operationType:CoreSession['kind'];base:PublishedWorld|null;initialManifest?:{worldId:string;title:string};changes:readonly WorldChange[];control:CandidateControlV1}):Promise<PublishedWorld>;stage(stage:SubmissionStageV2,attempt:number):void}):Promise<{published:PublishedWorld;diagnostics:readonly ValidationIssueV1[]}>{
 const snapshot=await input.draft.snapshot(),head=await input.draft.head();if(head.activeSession===null||head.activeSession.sessionId!==input.session.id||head.activeSession.pendingDraftSync!==null)throw new SubmissionPipelineErrorV2('DRAFT_CONFLICT','Draft is not clean or Session authority changed.');
 const candidateRoot=path.join(input.transientRoot,'submission-v2','candidate','files');await rm(path.dirname(candidateRoot),{recursive:true,force:true});await mkdir(candidateRoot,{recursive:true});
 try{input.stage('plan',1);let sealed;try{sealed=await input.planner.plan({session:input.session,draft:snapshot});}catch(error){throw new SubmissionPipelineErrorV2('CONVERSION_FAILED','Change Plan declaration failed.',[],{cause:error});}
  const {plan,assignment}=sealed;await verifyChangePlanEvidenceV2({plan,snapshot,turns:input.turns,worldRoot:input.worldRoot,world:input.session.pinned});await validateTargets(plan,input.session.pinned,input.worldRoot);if(plan.baseDraftHash!==snapshot.hash||plan.baseWorldCommitId!==(input.session.pinned?.commit.id??null)||plan.sessionKind!==input.session.kind||plan.targetDay!==input.session.day||assignment.planHash!==hashChangePlanV2(plan)||assignment.baseRootTreeHash!==(input.session.pinned?.commit.rootTreeHash??null))throw new SubmissionPipelineErrorV2('CONVERSION_FAILED','Sealed Change Plan baseline is inconsistent.');
  input.stage('convert',1);try{await input.converter.run({phase:'convert',attempt:1,session:input.session,draft:snapshot,plan,assignment,candidateRoot,diagnostics:[]});}catch(error){throw new SubmissionPipelineErrorV2('CONVERSION_FAILED','Markdown Draft conversion failed.',[],{cause:error});}
  const control=targetControl(input.session);let validated:PublishedWorld|null=null,validatedChanges:readonly Extract<WorldChange,{op:'put'}>[]|null=null,diagnostics:readonly ValidationIssueV1[]=[],previous:string|null=null,initialManifest:{worldId:string;title:string}|undefined;const validationHistory:ValidationIssueV1[]=[];
  for(let attempt=0;attempt<=SESSION_FILE_LIMITS.repairRounds;attempt++){input.stage('validate',attempt+1);try{const changes=await readCandidateWorkspaceV1(candidateRoot);initialManifest=input.session.kind==='init'?deriveInitialManifest(changes):undefined;const candidate=await assembleCandidateV1({worldRoot:input.worldRoot,operationType:input.session.kind,base:input.session.pinned,changes,control,initialManifest,allowedRevisePaths:allowedPaths(plan,assignment)}),result=await validateCandidateV1(candidate);if(result.ok){validated=result.world;validatedChanges=candidate.changes;diagnostics=[];break;}diagnostics=result.diagnostics;}catch(error){diagnostics=sortDiagnosticsV1([issue(error)]);}validationHistory.push(...diagnostics);await input.draft.writeDiagnostics(diagnostics);const signature=diagnostics.map((item)=>`${item.code}\0${item.path??''}\0${item.constraint}`).join('\n');if(attempt>=SESSION_FILE_LIMITS.repairRounds||signature===previous)break;previous=signature;input.stage('repair',attempt+1);try{await input.converter.run({phase:'repair',attempt:attempt+1,session:input.session,draft:snapshot,plan,assignment,candidateRoot,diagnostics});}catch(error){throw new SubmissionPipelineErrorV2('CONVERSION_FAILED','Candidate repair failed.',diagnostics,{cause:error});}}
  if(!validated)throw new SubmissionPipelineErrorV2('CANDIDATE_INVALID','Candidate validation failed.',diagnostics);input.stage('review',1);let review:{raw:unknown;advisory:readonly ValidationIssueV1[]};try{review=await input.reviewer.review({session:input.session,draft:snapshot,plan,assignment,candidateRoot});}catch(error){review={raw:null,advisory:[{schemaVersion:1,stage:'review',severity:'advisory',code:'REVIEW_UNAVAILABLE',path:null,constraint:message(error)}]};}const advisory=sortDiagnosticsV1(review.advisory);
  input.stage('diff',1);const diff=actualDiff(validatedChanges!,input.session.pinned);if(diff.length===0)throw new SubmissionPipelineErrorV2('CANDIDATE_INVALID','Candidate produces no World document changes.');const current=await input.draft.head();if(current.revision!==head.revision||current.draftHash!==snapshot.hash||current.activeSession?.pendingDraftSync!==null)throw new SubmissionPipelineErrorV2('DRAFT_CONFLICT','Draft authority changed before publish.');
  const transcript=await exportVisibleTranscriptV1(path.join(input.draft.root,'sessions',input.session.id,'conversations',head.activeSession.conversationId),'');const conversionRounds=await collectConversionRounds(path.join(input.transientRoot,'submission-v2'));const auditInput:SubmissionAuditInputV2={sessionId:input.session.id,kind:input.session.kind,snapshot,transcript,turns:input.turns,changePlan:plan,assignment,conversionRounds,validation:sortDiagnosticsV1(validationHistory),review:review.raw,reviewDiagnostics:advisory,candidateChanges:diff};const audit=await buildSubmissionAuditV2(auditInput),archive=await input.draft.prepareArchive(snapshot);let published:PublishedWorld;try{input.stage('publish',1);published=await input.publish({operationType:input.session.kind,base:input.session.pinned,initialManifest,changes:[...diff,...audit],control});}catch(error){await archive.rollback();throw error;}await archive.commit();return Object.freeze({published,diagnostics:advisory});
 }finally{await rm(path.join(input.transientRoot,'submission-v2'),{recursive:true,force:true}).catch(()=>undefined);}
}
function targetControl(session:CoreSession):CandidateControlV1{const previous=session.pinned?.commit.control.lastSettledDay??null;if(session.kind==='planning')return{phase:'planned',day:session.day,lastSettledDay:previous};if(session.kind==='play')return{phase:'awaiting-settle',day:session.day,lastSettledDay:previous};if(session.kind==='revise')return{...session.pinned!.commit.control};return{phase:'idle',day:null,lastSettledDay:null};}
function deriveInitialManifest(changes:readonly Extract<WorldChange,{op:'put'}>[]):{worldId:string;title:string}{const state=changes.find((item)=>item.path==='state/world.yaml');if(!state)throw new Error('Initial Candidate is missing state/world.yaml.');const parsed=YAML.parse(new TextDecoder().decode(state.bytes));const title=parsed?.title;if(typeof title!=='string'||title.trim()==='')throw new Error('Initial Candidate title is missing.');return{worldId:`world_${randomUUID().replaceAll('-','')}`,title:title.trim()};}
function allowedPaths(plan:Readonly<ChangePlanV2>,assignment:Readonly<ChangePlanAssignmentV2>):ReadonlySet<string>|undefined{if(plan.sessionKind!=='revise')return undefined;const paths=new Set<string>();for(const change of plan.changes){const id=change.action==='create'?assignment.assignedIds[change.localKey]:change.targetId;if(change.resourceKind==='canon-field')paths.add(`canon/${id.replace('userRole','user-role')}.md`);if(change.resourceKind==='character-profile')paths.add(`characters/${id}/profile.md`);if(change.resourceKind==='location-profile')paths.add(`locations/${id}/profile.md`);if(change.resourceKind==='arc-profile')paths.add(`arcs/${id}/profile.md`);if(change.resourceKind==='world-variable')paths.add('state/variables.yaml');if(change.resourceKind==='character-status'||change.resourceKind==='character-location')paths.add(`characters/${id}/state.yaml`);if(change.resourceKind==='location-status')paths.add(`locations/${id}/state.yaml`);if(change.resourceKind==='arc-stage')paths.add(`arcs/${id}/state.yaml`);if(change.resourceKind==='story-seed')paths.add('story-seeds/active.yaml');if(change.resourceKind==='character'&&change.action==='create'){paths.add('characters/index.yaml');for(const name of['profile.md','relationships.yaml','state.yaml','memory.md','timeline.md'])paths.add(`characters/${id}/${name}`);}if(change.resourceKind==='location'&&change.action==='create'){paths.add('locations/index.yaml');for(const name of['profile.md','state.yaml','memory.md','triggers.yaml','timeline.md'])paths.add(`locations/${id}/${name}`);}if(change.resourceKind==='arc'&&change.action==='create'){paths.add('arcs/index.yaml');for(const name of['profile.md','state.yaml','timeline.md'])paths.add(`arcs/${id}/${name}`);}}return paths;}
function actualDiff(changes:readonly Extract<WorldChange,{op:'put'}>[],base:PublishedWorld|null){const hashes=new Map(base?.tree.entries.map((entry)=>[entry.path,entry.blobHash])??[]);return changes.filter((change)=>hashes.get(change.path)!==hashBlobV1(change.bytes));}function issue(error:unknown):ValidationIssueV1{return{schemaVersion:1,stage:'candidate',severity:'error',code:'CANDIDATE_ASSEMBLY_FAILED',path:null,constraint:message(error)};}function message(error:unknown){return error instanceof Error?error.message:String(error);}
async function validateTargets(plan:Readonly<ChangePlanV2>,world:PublishedWorld|null,worldRoot:string):Promise<void>{if(plan.sessionKind==='init')return;if(!world)throw new Error('Change Plan target World is missing.');const characters=new Set(world.profileV1.characterIds),locations=new Set(world.profileV1.locationIds),arcs=new Set(world.profileV1.arcIds);let seeds:Set<string>|null=null;for(const change of plan.changes){if(change.action==='create')continue;const id=change.targetId;if(['character-profile','character-status','character-location'].includes(change.resourceKind)&&!characters.has(id))throw new Error(`Character target does not exist: ${id}.`);if(['location-profile','location-status'].includes(change.resourceKind)&&!locations.has(id))throw new Error(`Location target does not exist: ${id}.`);if(['arc-profile','arc-stage'].includes(change.resourceKind)&&!arcs.has(id))throw new Error(`Arc target does not exist: ${id}.`);if(change.resourceKind==='canon-field'&&!['premise','rules','style','userRole'].includes(id))throw new Error(`Canon field is invalid: ${id}.`);if(change.resourceKind==='story-seed'&&change.action==='remove'){if(seeds===null){const parsed=YAML.parse(await readTextDocument(worldRoot,world.tree,'story-seeds/active.yaml'));const rows=Array.isArray(parsed)?parsed:Array.isArray(parsed?.seeds)?parsed.seeds:[];seeds=new Set(rows.map((row:any)=>String(row.id??row.seedId??'')).filter(Boolean));}if(!seeds.has(id))throw new Error(`Story seed target does not exist: ${id}.`);}}}
async function collectConversionRounds(root:string):Promise<Array<{phase:'convert'|'repair';attempt:number;transcript:Awaited<ReturnType<typeof exportVisibleTranscriptV1>>}>>{const rounds:Array<{phase:'convert'|'repair';attempt:number;transcript:Awaited<ReturnType<typeof exportVisibleTranscriptV1>>}>=[];let entries;try{entries=await readdir(root,{withFileTypes:true});}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return rounds;throw error;}for(const entry of entries){const match=/^(convert|repair)-([1-9][0-9]*)$/.exec(entry.name);if(!entry.isDirectory()||!match)continue;try{rounds.push({phase:match[1] as 'convert'|'repair',attempt:Number(match[2]),transcript:await exportVisibleTranscriptV1(path.join(root,entry.name,'conversation'),'')});}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}}return rounds.sort((left,right)=>left.phase===right.phase?left.attempt-right.attempt:left.phase==='convert'?-1:1);}
