import { parseBlobHashV1 } from './blob';
import { ARCHIVE_PROTOCOL_ERROR_CODES, protocolError, type ArchiveProtocolErrorCode, type JsonScalar } from './errors';
import { deepFreeze, exactKeys, integer, nullable, record, schemaVersion, stableId, string, timestamp } from './parse';
export type ArchiveOperationStatusV2='open'|'prepared'|'published'|'aborted';
export type ArchiveOperationErrorSourceV1='protocol'|'runtime'|'tool';
export interface ArchiveOperationErrorV1{source:ArchiveOperationErrorSourceV1;code:string;message:string;details?:Readonly<Record<string,JsonScalar>>}
export interface ArchiveOperationV2{schemaVersion:2;id:string;type:string;status:ArchiveOperationStatusV2;baseRevision:number;baseCommitId:string|null;baseRootTreeHash:string|null;targetCommitId:string|null;targetRootTreeHash:string|null;createdAt:string;updatedAt:string;lastError:ArchiveOperationErrorV1|null}
export function parseArchiveOperationV2(value:unknown):Readonly<ArchiveOperationV2>{
 const o=record(value,'ArchiveOperationV2','ARCHIVE_PROTOCOL_OPERATION_INVALID');exactKeys(o,['schemaVersion','id','type','status','baseRevision','baseCommitId','baseRootTreeHash','targetCommitId','targetRootTreeHash','createdAt','updatedAt','lastError'],'ArchiveOperationV2','ARCHIVE_PROTOCOL_OPERATION_INVALID');schemaVersion(o.schemaVersion,2,'ArchiveOperationV2');if(o.status!=='open'&&o.status!=='prepared'&&o.status!=='published'&&o.status!=='aborted')protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','ArchiveOperationV2.status is invalid.');
 const baseRevision=integer(o.baseRevision,'ArchiveOperationV2','baseRevision',0,'ARCHIVE_PROTOCOL_OPERATION_INVALID'),baseCommitId=nullable(o.baseCommitId,v=>stableId(v,'ArchiveOperationV2','baseCommitId','ARCHIVE_PROTOCOL_OPERATION_INVALID')),baseRootTreeHash=nullable(o.baseRootTreeHash,v=>parseBlobHashV1(v,'baseRootTreeHash')),targetCommitId=nullable(o.targetCommitId,v=>stableId(v,'ArchiveOperationV2','targetCommitId','ARCHIVE_PROTOCOL_OPERATION_INVALID')),targetRootTreeHash=nullable(o.targetRootTreeHash,v=>parseBlobHashV1(v,'targetRootTreeHash'));
 const isEmptyBase=baseRevision===0,baseRefsEmpty=baseCommitId===null&&baseRootTreeHash===null,baseRefsComplete=baseCommitId!==null&&baseRootTreeHash!==null;if((isEmptyBase&&!baseRefsEmpty)||(!isEmptyBase&&!baseRefsComplete))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','Operation base revision and references must be either wholly empty or wholly populated.');const hasTarget=targetCommitId!==null&&targetRootTreeHash!==null;if((targetCommitId===null)!==(targetRootTreeHash===null)||((o.status==='prepared'||o.status==='published')&&!hasTarget)||((o.status==='open')&&hasTarget))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','Operation target references do not match its status.');
 return deepFreeze({schemaVersion:2,id:stableId(o.id,'ArchiveOperationV2','id','ARCHIVE_PROTOCOL_OPERATION_INVALID'),type:string(o.type,'ArchiveOperationV2','type',false,'ARCHIVE_PROTOCOL_OPERATION_INVALID'),status:o.status,baseRevision,baseCommitId,baseRootTreeHash,targetCommitId,targetRootTreeHash,createdAt:timestamp(o.createdAt,'ArchiveOperationV2','createdAt','ARCHIVE_PROTOCOL_OPERATION_INVALID'),updatedAt:timestamp(o.updatedAt,'ArchiveOperationV2','updatedAt','ARCHIVE_PROTOCOL_OPERATION_INVALID'),lastError:nullable(o.lastError,parseErrorData)});
}
function parseErrorData(value:unknown):ArchiveOperationErrorV1{const o=record(value,'ArchiveOperationErrorV1','ARCHIVE_PROTOCOL_OPERATION_INVALID');const keys=['source','code','message',...(o.details===undefined?[]:['details'])];exactKeys(o,keys,'ArchiveOperationErrorV1','ARCHIVE_PROTOCOL_OPERATION_INVALID');if(o.source!=='protocol'&&o.source!=='runtime'&&o.source!=='tool')protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','lastError.source is invalid.');const code=string(o.code,'ArchiveOperationErrorV1','code');if(o.source==='protocol'&&!(ARCHIVE_PROTOCOL_ERROR_CODES as readonly string[]).includes(code))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','Protocol diagnostic code is not an Archive Protocol error code.');const result:ArchiveOperationErrorV1={source:o.source,code:o.source==='protocol'?code as ArchiveProtocolErrorCode:code,message:string(o.message,'ArchiveOperationErrorV1','message')};if(o.details!==undefined){const details=record(o.details,'ArchiveOperationErrorV1.details','ARCHIVE_PROTOCOL_OPERATION_INVALID');for(const v of Object.values(details))if(v!==null&&!['string','number','boolean'].includes(typeof v)||typeof v==='number'&&!Number.isFinite(v))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','lastError.details must contain finite scalar JSON values.');result.details=details as Record<string,JsonScalar>;}return result;}
