import { parseBlobHashV1 } from './blob';
import { ARCHIVE_PROTOCOL_ERROR_CODES, protocolError, type ArchiveProtocolErrorData } from './errors';
import { deepFreeze, exactKeys, integer, nullable, record, schemaVersion, stableId, string, timestamp } from './parse';
export type ArchiveOperationStatusV2='open'|'prepared'|'published'|'aborted';
export interface ArchiveOperationV2{schemaVersion:2;id:string;type:string;status:ArchiveOperationStatusV2;baseRevision:number;baseCommitId:string|null;baseRootTreeHash:string|null;targetCommitId:string|null;targetRootTreeHash:string|null;createdAt:string;updatedAt:string;lastError:ArchiveProtocolErrorData|null}
export function parseArchiveOperationV2(value:unknown):Readonly<ArchiveOperationV2>{
 const o=record(value,'ArchiveOperationV2','ARCHIVE_PROTOCOL_OPERATION_INVALID');exactKeys(o,['schemaVersion','id','type','status','baseRevision','baseCommitId','baseRootTreeHash','targetCommitId','targetRootTreeHash','createdAt','updatedAt','lastError'],'ArchiveOperationV2','ARCHIVE_PROTOCOL_OPERATION_INVALID');schemaVersion(o.schemaVersion,2,'ArchiveOperationV2');if(o.status!=='open'&&o.status!=='prepared'&&o.status!=='published'&&o.status!=='aborted')protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','ArchiveOperationV2.status is invalid.');
 const baseRevision=integer(o.baseRevision,'ArchiveOperationV2','baseRevision',0,'ARCHIVE_PROTOCOL_OPERATION_INVALID'),baseCommitId=nullable(o.baseCommitId,v=>stableId(v,'ArchiveOperationV2','baseCommitId','ARCHIVE_PROTOCOL_OPERATION_INVALID')),baseRootTreeHash=nullable(o.baseRootTreeHash,v=>parseBlobHashV1(v,'baseRootTreeHash')),targetCommitId=nullable(o.targetCommitId,v=>stableId(v,'ArchiveOperationV2','targetCommitId','ARCHIVE_PROTOCOL_OPERATION_INVALID')),targetRootTreeHash=nullable(o.targetRootTreeHash,v=>parseBlobHashV1(v,'targetRootTreeHash'));
 if((baseRevision===0)!==(baseCommitId===null&&baseRootTreeHash===null))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','Empty base references are inconsistent.');const hasTarget=targetCommitId!==null&&targetRootTreeHash!==null;if((targetCommitId===null)!==(targetRootTreeHash===null)||((o.status==='prepared'||o.status==='published')&&!hasTarget)||((o.status==='open')&&hasTarget))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','Operation target references do not match its status.');
 return deepFreeze({schemaVersion:2,id:stableId(o.id,'ArchiveOperationV2','id','ARCHIVE_PROTOCOL_OPERATION_INVALID'),type:string(o.type,'ArchiveOperationV2','type',false,'ARCHIVE_PROTOCOL_OPERATION_INVALID'),status:o.status,baseRevision,baseCommitId,baseRootTreeHash,targetCommitId,targetRootTreeHash,createdAt:timestamp(o.createdAt,'ArchiveOperationV2','createdAt','ARCHIVE_PROTOCOL_OPERATION_INVALID'),updatedAt:timestamp(o.updatedAt,'ArchiveOperationV2','updatedAt','ARCHIVE_PROTOCOL_OPERATION_INVALID'),lastError:nullable(o.lastError,parseErrorData)});
}
function parseErrorData(value:unknown):ArchiveProtocolErrorData{const o=record(value,'ArchiveProtocolErrorData','ARCHIVE_PROTOCOL_OPERATION_INVALID');const keys=['code','message',...(o.details===undefined?[]:['details'])];exactKeys(o,keys,'ArchiveProtocolErrorData','ARCHIVE_PROTOCOL_OPERATION_INVALID');if(typeof o.code!=='string'||!(ARCHIVE_PROTOCOL_ERROR_CODES as readonly string[]).includes(o.code))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','lastError.code is invalid.');const result:ArchiveProtocolErrorData={code:o.code as ArchiveProtocolErrorData['code'],message:string(o.message,'ArchiveProtocolErrorData','message')};if(o.details!==undefined){const details=record(o.details,'ArchiveProtocolErrorData.details','ARCHIVE_PROTOCOL_OPERATION_INVALID');for(const v of Object.values(details))if(v!==null&&!['string','number','boolean'].includes(typeof v))protocolError('ARCHIVE_PROTOCOL_OPERATION_INVALID','lastError.details must contain scalar JSON values.');result.details=details as ArchiveProtocolErrorData['details'];}return result;}
