import { parseBlobHashV1 } from './blob';
import { protocolError } from './errors';
import { parseArchiveMediaTypeV1, type ArchiveMediaTypeV1 } from './media';
import { deepFreeze, exactKeys, integer, nullable, record, schemaVersion, stableId } from './parse';
import { compareWorldDocumentPathsV1, parseWorldDocumentPathV1, portableCollisionKeyV1 } from './path';
import { createRootTreeV1, parseRootTreeV1, type DocumentTreeEntryV1, type RootTreeV1 } from './tree';
export type StagedChangeV1={op:'put';path:string;mediaType:ArchiveMediaTypeV1;bytes:number;sha256:string;fileId:string}|{op:'delete';path:string};
export interface StagingManifestV1{schemaVersion:1;baseRevision:number;baseCommitId:string|null;baseRootTreeHash:string|null;changes:StagedChangeV1[]}
export function parseStagingManifestV1(value:unknown):Readonly<StagingManifestV1>{
 const o=record(value,'StagingManifestV1'); exactKeys(o,['schemaVersion','baseRevision','baseCommitId','baseRootTreeHash','changes'],'StagingManifestV1'); schemaVersion(o.schemaVersion,1,'StagingManifestV1'); if(!Array.isArray(o.changes)) protocolError('ARCHIVE_PROTOCOL_SHAPE_INVALID','StagingManifestV1.changes must be an array.');
 const changes=o.changes.map((item,i)=>parseChange(item,i)); let previous:string|undefined; const portable=new Set<string>(); for(const change of changes){const key=portableCollisionKeyV1(change.path);if(portable.has(key))protocolError('ARCHIVE_PROTOCOL_PATH_COLLISION','Staging changes contain a path collision.',{path:change.path});portable.add(key);if(previous!==undefined&&compareWorldDocumentPathsV1(previous,change.path)>=0)protocolError('ARCHIVE_PROTOCOL_SHAPE_INVALID','Staging changes must be in canonical order.');previous=change.path;}
 const baseRevision=integer(o.baseRevision,'StagingManifestV1','baseRevision',0); const baseCommitId=nullable(o.baseCommitId,v=>stableId(v,'StagingManifestV1','baseCommitId')); const baseRootTreeHash=nullable(o.baseRootTreeHash,v=>parseBlobHashV1(v,'baseRootTreeHash')); if((baseRevision===0)!==(baseCommitId===null&&baseRootTreeHash===null))protocolError('ARCHIVE_PROTOCOL_REFERENCE_INVALID','An empty base must use revision 0 and null references.');
 return deepFreeze({schemaVersion:1,baseRevision,baseCommitId,baseRootTreeHash,changes});
}
function parseChange(value:unknown,index:number):StagedChangeV1{const s=`StagingManifestV1.changes[${index}]`,o=record(value,s);if(o.op==='put'){exactKeys(o,['op','path','mediaType','bytes','sha256','fileId'],s);return{op:'put',path:parseWorldDocumentPathV1(o.path),mediaType:parseArchiveMediaTypeV1(o.mediaType),bytes:integer(o.bytes,s,'bytes',0),sha256:parseBlobHashV1(o.sha256,`${s}.sha256`),fileId:stableId(o.fileId,s,'fileId')}}if(o.op==='delete'){exactKeys(o,['op','path'],s);return{op:'delete',path:parseWorldDocumentPathV1(o.path)}}protocolError('ARCHIVE_PROTOCOL_SHAPE_INVALID',`${s}.op must be put or delete.`);}
export function overlayRootTreeV1(base:RootTreeV1,staging:StagingManifestV1):Readonly<RootTreeV1>{const parsedBase=parseRootTreeV1(base),parsedStaging=parseStagingManifestV1(staging);const entries=new Map<string,DocumentTreeEntryV1>(parsedBase.entries.map(e=>[e.path,e]));for(const change of parsedStaging.changes){if(change.op==='delete')entries.delete(change.path);else entries.set(change.path,{path:change.path,blobHash:change.sha256,mediaType:change.mediaType,bytes:change.bytes});}return createRootTreeV1([...entries.values()]);}
