import type { DomainPatchV1, ReviseSubmissionV2 } from '../../session/submission-v2';
import type { PublishedWorld } from '../read';
import type { WorldChange } from '../publish';
import { parseYamlObjectV1 } from '../profile/yaml';
import { markdown, yamlDocument } from './encode';

export function buildReviseMutationV1(world: PublishedWorld, submission: ReviseSubmissionV2): WorldChange[] {
  const docs = world.profileV1.contextDocuments, objects = new Map<string, Record<string, unknown>>(), changed = new Set<string>(), text = new Map<string, string>(), targets = new Set<string>();
  const allocated = { character: [...world.profileV1.characterIds], location: [...world.profileV1.locationIds], arc: [...world.profileV1.arcIds] };
  const object = (path: string) => { let value = objects.get(path); if (!value) { value = parseYamlObjectV1(required(docs, path), path); objects.set(path, value); } return value; };
  for (const operation of submission.operations) {
    const target = targetOf(operation); if (!operation.op.startsWith('create-') && targets.has(target)) throw new Error(`Revise contains conflicting writes to ${target}.`); targets.add(target);
    if (operation.op === 'replace-canon') { const path = `canon/${operation.field === 'userRole' ? 'user-role' : operation.field}.md`; expect(required(docs, path), operation.expected); text.set(path, operation.value); continue; }
    if (operation.op === 'replace-character-profile' || operation.op === 'replace-location-profile' || operation.op === 'replace-arc-profile') { const kind = operation.op === 'replace-character-profile' ? 'character' : operation.op === 'replace-location-profile' ? 'location' : 'arc'; const id = operation.op === 'replace-character-profile' ? operation.characterId : operation.op === 'replace-location-profile' ? operation.locationId : operation.arcId; requireId(world, kind, id); const path = `${kind === 'character' ? 'characters' : `${kind}s`}/${id}/profile.md`; expect(required(docs, path), operation.expected); text.set(path, operation.value); continue; }
    if (operation.op === 'create-character') { if (operation.locationId !== null && !allocated.location.includes(operation.locationId) || operation.relationships.some((relation) => !allocated.character.includes(relation.characterId))) throw new Error('Revise create-character reference is invalid.'); const id = allocate('character', allocated.character), index = object('characters/index.yaml'); (index.ids as unknown[]).push(id); changed.add('characters/index.yaml'); text.set(`characters/${id}/profile.md`, operation.profile); text.set(`characters/${id}/memory.md`, ''); text.set(`characters/${id}/timeline.md`, ''); objects.set(`characters/${id}/state.yaml`, { schemaVersion: 1, status: operation.status, locationId: operation.locationId, tags: operation.tags }); changed.add(`characters/${id}/state.yaml`); objects.set(`characters/${id}/relationships.yaml`, { schemaVersion: 1, relationships: operation.relationships }); changed.add(`characters/${id}/relationships.yaml`); continue; }
    if (operation.op === 'create-location') { const id = allocate('location', allocated.location), index = object('locations/index.yaml'); (index.ids as unknown[]).push(id); changed.add('locations/index.yaml'); text.set(`locations/${id}/profile.md`, operation.profile); text.set(`locations/${id}/memory.md`, ''); text.set(`locations/${id}/timeline.md`, ''); objects.set(`locations/${id}/state.yaml`, { schemaVersion: 1, status: operation.status, tags: operation.tags }); changed.add(`locations/${id}/state.yaml`); objects.set(`locations/${id}/triggers.yaml`, { schemaVersion: 1, triggers: operation.triggers.map((trigger, index) => ({ id: `trigger${index + 1}`, ...trigger })) }); changed.add(`locations/${id}/triggers.yaml`); continue; }
    if (operation.op === 'create-arc') { const id = allocate('arc', allocated.arc), index = object('arcs/index.yaml'); (index.ids as unknown[]).push(id); changed.add('arcs/index.yaml'); text.set(`arcs/${id}/profile.md`, operation.profile); text.set(`arcs/${id}/timeline.md`, ''); objects.set(`arcs/${id}/state.yaml`, { schemaVersion: 1, status: operation.status, stage: operation.stage, progress: null }); changed.add(`arcs/${id}/state.yaml`); if (operation.status === 'active') { const progress = object('state/progress.yaml'); (progress.activeArcIds as unknown[]).push(id); changed.add('state/progress.yaml'); } continue; }
    if (operation.op === 'add-story-seed' || operation.op === 'remove-story-seed') { const path = 'story-seeds/active.yaml', doc = object(path), seeds = array(doc.seeds); if (operation.op === 'add-story-seed') seeds.push({ id: `seed${nextId(seeds, 'seed')}`, text: operation.text, origin: 'revise' }); else { const index = seeds.findIndex((item) => record(item).id === operation.seedId); if (index < 0 || record(seeds[index]).text !== operation.expectedText) throw new Error('Story seed precondition failed.'); seeds.splice(index, 1); } changed.add(path); continue; }
    applyState(world, operation as DomainPatchV1, object, changed);
  }
  return [...text].map(([path, value]) => markdown(path, value)).concat([...changed].map((path) => yamlDocument(path, objects.get(path)!)));
}
function applyState(world: PublishedWorld, op: DomainPatchV1, object: (path: string) => Record<string, unknown>, changed: Set<string>) {
  if (op.op === 'set-world-variable') { const path = 'state/variables.yaml', vars = object(path).variables as Record<string, unknown>; expect(vars[op.key] ?? null, op.expected); vars[op.key] = op.value; changed.add(path); return; }
  if (op.op === 'set-character-status' || op.op === 'move-character') { requireId(world, 'character', op.characterId); const path = `characters/${op.characterId}/state.yaml`, doc = object(path); if (op.op === 'set-character-status') { expect(doc.status, op.expected); doc.status = op.value; } else { if (op.locationId !== null) requireId(world, 'location', op.locationId); expect(doc.locationId ?? null, op.expectedLocationId); doc.locationId = op.locationId; } changed.add(path); return; }
  if (op.op === 'set-location-status') { requireId(world, 'location', op.locationId); const path = `locations/${op.locationId}/state.yaml`, doc = object(path); expect(doc.status, op.expected); doc.status = op.value; changed.add(path); return; }
  requireId(world, 'arc', op.arcId); const path = `arcs/${op.arcId}/state.yaml`, doc = object(path); expect(doc.stage, op.expected); doc.stage = op.value; changed.add(path);
}
function targetOf(op: ReviseSubmissionV2['operations'][number]): string { return JSON.stringify(op.op === 'set-world-variable' ? [op.op, op.key] : op.op === 'replace-canon' ? [op.op, op.field] : op.op === 'add-story-seed' ? [op.op, op.text] : op.op === 'remove-story-seed' ? ['story-seed', op.seedId] : op.op === 'create-character' || op.op === 'create-location' || op.op === 'create-arc' ? [op.op] : 'characterId' in op ? [op.op, op.characterId] : 'locationId' in op ? [op.op, op.locationId] : [op.op, op.arcId]); }
function requireId(world: PublishedWorld, kind: string, id: string) { const ids = kind === 'character' ? world.profileV1.characterIds : kind === 'location' ? world.profileV1.locationIds : world.profileV1.arcIds; if (!ids.includes(id)) throw new Error(`Revise ${kind} reference is invalid.`); }
function required(docs: Readonly<Record<string, string>>, path: string) { const value = docs[path]; if (value === undefined) throw new Error(`Revise document is missing: ${path}`); return value; }
function expect(actual: unknown, expected: unknown) { if (!Object.is(actual, expected)) throw new Error('Revise precondition failed.'); }
function array(value: unknown): unknown[] { if (!Array.isArray(value)) throw new Error('Revise collection is invalid.'); return value; }
function record(value: unknown): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new Error('Revise item is invalid.'); return value as Record<string, unknown>; }
function nextId(items: unknown[], prefix: string): number { let value = 1; const ids = new Set(items.map((item) => String(record(item).id))); while (ids.has(`${prefix}${value}`)) value++; return value; }
function allocate(prefix: 'character' | 'location' | 'arc', ids: string[]): string { let value = 1; while (ids.includes(`${prefix}${value}`)) value++; const id = `${prefix}${value}`; ids.push(id); return id; }
