import { createRuntimeError } from '../errors';
import type { CanonDocuments } from '../schemas/submissions';
import type { SessionDayContext, SessionWorldReadModel } from '../sessions/world-read-model';
import type { WorldSnapshot } from '../types';
import { DAYLOOM_CANON_PATHS, dayDocumentPath } from './profile';
import type { ArchiveV2Repository } from './types';

export function createArchiveV2SessionWorldReadModel(archive:ArchiveV2Repository):SessionWorldReadModel{return{
 async read(snapshot:Readonly<WorldSnapshot>){const current=await archive.readCurrent();if(!snapshot.initialized||snapshot.commitId===null)return{canon:null,day:null};if(current.status!=='ready')throw createRuntimeError('ARCHIVE_CONFLICT','Session World is no longer published.');if(current.pointer.revision!==snapshot.revision||current.pointer.commitId!==snapshot.commitId)throw createRuntimeError('ARCHIVE_CONFLICT','Session snapshot no longer matches current.',{snapshotRevision:snapshot.revision,currentRevision:current.pointer.revision});const canon=await readCanon(archive);const day=snapshot.day?await readDay(archive,snapshot.day):null;return{canon,day};
 }};}
async function readCanon(archive:ArchiveV2Repository):Promise<CanonDocuments|null>{const values=await Promise.all(Object.values(DAYLOOM_CANON_PATHS).map(p=>archive.readPublishedDocument(p)));if(values.every(v=>v===null))return null;const text=(v:Uint8Array|null)=>v?new TextDecoder().decode(v):'';return{premise:text(values[0]),rules:text(values[1]),style:text(values[2]),userRole:text(values[3])};}
async function readDay(archive:ArchiveV2Repository,day:string):Promise<SessionDayContext|null>{const planBytes=await archive.readPublishedDocument(dayDocumentPath(day,'plan'));if(!planBytes)return null;const planJson=JSON.parse(new TextDecoder().decode(planBytes));const playBytes=await archive.readPublishedDocument(dayDocumentPath(day,'play')),summaryBytes=await archive.readPublishedDocument(dayDocumentPath(day,'summary'));const playJson=playBytes?JSON.parse(new TextDecoder().decode(playBytes)):null;return{meta:{day,revision:'dayrev_document_profile',parentRevision:null,operationId:'op_document_profile',status:playJson?'awaiting-settle':'planned',createdAt:'1970-01-01T00:00:00.000Z',files:[]},plan:{day,intent:planJson.intent,beats:planJson.beats},play:playJson?{day,summary:summaryBytes?new TextDecoder().decode(summaryBytes):'',eventIds:(playJson.events??[]).map((event:{id:string})=>event.id)}:null,events:playJson?.events??[],transcript:playJson?.transcript??[],settlement:null,abandoned:null};}
