const assert=require('node:assert/strict');const {readFile}=require('node:fs/promises');const path=require('node:path');const test=require('node:test');const p=require('../dist');
const fixtures=path.resolve(__dirname,'../../../fixtures/archive-protocol/v2');const json=async(...parts)=>JSON.parse(await readFile(path.join(fixtures,...parts),'utf8'));
const hash='5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03';
test('strict parsers accept and freeze valid V2 fixtures',async()=>{for(const [file,parse] of [['manifest.json',p.parseArchiveManifestV2],['current.json',p.parseCurrentPointerV2],['commit.json',p.parseArchiveCommitV2]]){const value=parse(await json('valid',file));assert(Object.isFrozen(value));}const manifest=await json('valid','manifest.json');assert.throws(()=>p.parseArchiveManifestV2({...manifest,extra:true}),{code:'ARCHIVE_PROTOCOL_SHAPE_INVALID'});});
test('unsupported versions fail closed',async()=>{const manifest=await json('invalid','unsupported-manifest.json');assert.throws(()=>p.parseArchiveManifestV2(manifest),{code:'ARCHIVE_PROTOCOL_VERSION_UNSUPPORTED'});});
test('path normalization is explicit while stored paths must be canonical',()=>{assert.equal(p.normalizeWorldDocumentPathV1('cafe\u0301/note.md'),'café/note.md');assert.throws(()=>p.parseWorldDocumentPathV1('cafe\u0301/note.md'),{code:'ARCHIVE_PROTOCOL_PATH_INVALID'});for(const invalid of ['../x','C:/x','a\\b','.dayloom/x','aux.txt','a//b','a./'])assert.throws(()=>p.parseWorldDocumentPathV1(invalid),{code:'ARCHIVE_PROTOCOL_PATH_INVALID'});});
test('portable collisions and non-canonical order are rejected',async()=>{const collision=await json('invalid','path-collision-tree.json');assert.throws(()=>p.parseRootTreeV1(collision),{code:'ARCHIVE_PROTOCOL_PATH_COLLISION'});assert.throws(()=>p.parseRootTreeV1({schemaVersion:1,entries:[entry('z'),entry('a')]}),{code:'ARCHIVE_PROTOCOL_TREE_INVALID'});});
test('canonical tree bytes and hash match golden fixtures',async()=>{const tree=await json('canonical','root-tree.json');const expected=await readFile(path.join(fixtures,'canonical','root-tree.json'));const expectedHash=(await readFile(path.join(fixtures,'canonical','root-tree.sha256'),'utf8')).trim();assert.deepEqual(Buffer.from(p.encodeRootTreeCanonicalV1(tree)),expected);assert.equal(p.hashRootTreeV1(tree),expectedHash);});
test('blob and content validation are deterministic',()=>{const bytes=Buffer.from('hello\n');assert.equal(p.hashBlobV1(bytes),hash);p.verifyBlobV1(bytes,hash,6);p.validateContentV1(Buffer.from('{"ok":true}'),'application/json');p.validateContentV1(Buffer.from('ok: true\n'),'application/yaml');assert.throws(()=>p.validateContentV1(Buffer.from('{'),'application/json'),{code:'ARCHIVE_PROTOCOL_MEDIA_INVALID'});});
test('PUT/DELETE overlay is final-state and delete-missing is idempotent',()=>{const base=p.createRootTreeV1([entry('a')]);const staging={schemaVersion:1,baseRevision:1,baseCommitId:'commit_001',baseRootTreeHash:'27d96125ceeb206b70591066493ca295df224b1eeaee83fd25d67525ba186f10',changes:[{op:'delete',path:'a'},{op:'delete',path:'missing'},{op:'put',path:'z',mediaType:'text/plain',bytes:6,sha256:hash,fileId:'file_1'}]};assert.deepEqual(p.overlayRootTreeV1(base,staging).entries.map(e=>e.path),['z']);});
test('prepared operation recovery uses durable current facts',async()=>{const facts=await json('graphs','recovery.json');const op=operation();assert.equal(p.classifyOperationRecoveryV2({operation:op,current:facts.base}),'not-published');assert.equal(p.classifyOperationRecoveryV2({operation:op,current:facts.target}),'already-published');assert.equal(p.classifyOperationRecoveryV2({operation:op,current:{...facts.target,commitId:'commit_other'}}),'superseded');});
test('layout and graph helpers stay archive-relative and detect cycles',()=>{assert.equal(p.formatBlobObjectPathV1(hash),`objects/blobs/sha256/${hash}`);const a=commit('a','b',1),b=commit('b','a',2);assert.throws(()=>p.validateCommitParentGraphV2(new Map([['a',a],['b',b]])),{code:'ARCHIVE_PROTOCOL_REFERENCE_INVALID'});});
function entry(pathname){return{path:pathname,blobHash:hash,mediaType:'text/plain',bytes:6}}function operation(){return{schemaVersion:2,id:'op_002',type:'test',status:'prepared',baseRevision:1,baseCommitId:'commit_001',baseRootTreeHash:hash,targetCommitId:'commit_002',targetRootTreeHash:hash,createdAt:'2026-08-13T00:00:00.000Z',updatedAt:'2026-08-13T00:00:01.000Z',lastError:null}}function commit(id,parent,revision){return{schemaVersion:2,id,revision,parentCommitId:parent,operationId:'op_1',createdAt:'2026-08-13T00:00:00.000Z',rootTreeHash:hash,control:{phase:'idle',day:null,lastSettledDay:null}}}
